"""fix

Revision ID: 0328d002c7bd
Revises: ef7531e77eed
Create Date: 2026-07-19 17:06:22.896881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0328d002c7bd'
down_revision: Union[str, Sequence[str], None] = 'ef7531e77eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'manager', 'admin', name='userrole'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'manager', 'admin', name='userrole'),
               server_default=sa.text("'customer'::userrole"),
               existing_nullable=False)
    # ### end Alembic commands ###
