"""fixe 23.07

Revision ID: 0c27ad17ee23
Revises: fed232f78d46
Create Date: 2026-07-23 20:22:12.957784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c27ad17ee23'
down_revision: Union[str, Sequence[str], None] = 'fed232f78d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'info_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Внешний ключ к информации о номере')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'info_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Внешний ключ к информации о номере')
    # ### end Alembic commands ###
