"""many-to-many table for user and hotel tables

Revision ID: 172ebfdca08a
Revises: c666886ad820
Create Date: 2026-07-11 12:05:11.188383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '172ebfdca08a'
down_revision: Union[str, Sequence[str], None] = 'c666886ad820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_hotels',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hotels_id'), 'users_hotels', ['id'], unique=False)
    op.alter_column('hotels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('hotels_user_id_fkey'), 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('hotels_user_id_fkey'), 'hotels', 'users', ['user_id'], ['id'])
    op.alter_column('hotels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_users_hotels_id'), table_name='users_hotels')
    op.drop_table('users_hotels')
    # ### end Alembic commands ###
