"""new table VerificationCode

Revision ID: 1bbb8d5e23f8
Revises: 72dd6f5dc431
Create Date: 2026-07-22 20:49:02.456152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbb8d5e23f8'
down_revision: Union[str, Sequence[str], None] = '72dd6f5dc431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_verifications',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Внешний ключ к пользователю'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='Код'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус кода'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Время окончания действия кода'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_verifications_id'), 'code_verifications', ['id'], unique=False)
    op.create_index('ix_user_code_active', 'code_verifications', ['user_id', 'code', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_code_active', table_name='code_verifications')
    op.drop_index(op.f('ix_code_verifications_id'), table_name='code_verifications')
    op.drop_table('code_verifications')
    # ### end Alembic commands ###
