"""payment tables and logic in other tables

Revision ID: 1caf657bde68
Revises: 085d26a1c36a
Create Date: 2026-07-21 18:21:07.683699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1caf657bde68'
down_revision: Union[str, Sequence[str], None] = '085d26a1c36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('reservations', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Дата от',
               existing_nullable=False)
    op.alter_column('reservations', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Дата до',
               existing_nullable=True)
    op.drop_constraint(op.f('reservations_user_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('room_information', 'price_per_night',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='Цена за сутки',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_information', 'price_per_night',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Цена за сутки',
               existing_nullable=False)
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_user_id_fkey'), 'reservations', 'users', ['user_id'], ['id'])
    op.alter_column('reservations', 'date_to',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Дата до',
               existing_nullable=True)
    op.alter_column('reservations', 'date_from',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Дата от',
               existing_nullable=False)
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###
