"""new table Reservation

Revision ID: 1ed917ab7227
Revises: 22db2925d76d
Create Date: 2026-07-09 11:24:18.502787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed917ab7227'
down_revision: Union[str, Sequence[str], None] = '22db2925d76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Внешний ключ к номеру'),
    sa.Column('date_from', sa.DateTime(), nullable=False, comment='Дата от'),
    sa.Column('date_to', sa.DateTime(), nullable=True, comment='Дата до'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.alter_column('hotels', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='Название отеля',
               existing_nullable=False)
    op.alter_column('hotels', 'city',
               existing_type=sa.VARCHAR(length=300),
               comment='Город местоположения',
               existing_nullable=False)
    op.alter_column('hotels', 'address',
               existing_type=sa.VARCHAR(length=300),
               comment='Адрес',
               existing_nullable=False)
    op.alter_column('hotels', 'region',
               existing_type=sa.VARCHAR(length=300),
               comment='Регион',
               existing_nullable=False)
    op.alter_column('hotels', 'description',
               existing_type=sa.TEXT(),
               comment='Описание',
               existing_nullable=True)
    op.alter_column('hotels', 'stars',
               existing_type=sa.INTEGER(),
               comment='Количество звезд',
               existing_nullable=False)
    op.alter_column('hotels', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Номер телефона',
               existing_nullable=True)
    op.alter_column('hotels', 'email',
               existing_type=sa.VARCHAR(length=300),
               comment='Почта',
               existing_nullable=True)
    op.alter_column('rooms', 'hotel_id',
               existing_type=sa.INTEGER(),
               comment='Внешний ключ к отелю',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'hotel_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Внешний ключ к отелю',
               existing_nullable=False)
    op.alter_column('hotels', 'email',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Почта',
               existing_nullable=True)
    op.alter_column('hotels', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Номер телефона',
               existing_nullable=True)
    op.alter_column('hotels', 'stars',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество звезд',
               existing_nullable=False)
    op.alter_column('hotels', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание',
               existing_nullable=True)
    op.alter_column('hotels', 'region',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Регион',
               existing_nullable=False)
    op.alter_column('hotels', 'address',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Адрес',
               existing_nullable=False)
    op.alter_column('hotels', 'city',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Город местоположения',
               existing_nullable=False)
    op.alter_column('hotels', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Название отеля',
               existing_nullable=False)
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
