"""mixin test

Revision ID: 22db2925d76d
Revises: e14fbf459c38
Create Date: 2026-07-08 18:23:23.073907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22db2925d76d'
down_revision: Union[str, Sequence[str], None] = 'e14fbf459c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('hotels_owner_id_fkey'), 'hotels', type_='foreignkey')
    op.create_foreign_key(None, 'hotels', 'users', ['user_id'], ['id'], ondelete='NO ACTION')
    op.drop_column('hotels', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.create_foreign_key(op.f('hotels_owner_id_fkey'), 'hotels', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hotels', 'user_id')
    # ### end Alembic commands ###
