"""fix Payment table for top-up operations

Revision ID: 3c23a5413137
Revises: 1bbb8d5e23f8
Create Date: 2026-07-23 09:14:05.027014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c23a5413137'
down_revision: Union[str, Sequence[str], None] = '1bbb8d5e23f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'reservation_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID бронирования (NULL если это пополнение счета)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'reservation_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='ID бронирования (NULL если это пополнение счета)')
    # ### end Alembic commands ###
