"""add column total_price to Reservation

Revision ID: 4cefbcf127c5
Revises: 0c27ad17ee23
Create Date: 2026-07-23 20:28:18.724051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cefbcf127c5'
down_revision: Union[str, Sequence[str], None] = '0c27ad17ee23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'total_price')
    # ### end Alembic commands ###
