"""owner in hotel

Revision ID: 5232d7fe84c4
Revises: fee56735218a
Create Date: 2026-07-08 12:47:51.599228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5232d7fe84c4'
down_revision: Union[str, Sequence[str], None] = 'fee56735218a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotels', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'owner_id')
    # ### end Alembic commands ###
