"""switch columns

Revision ID: 72dd6f5dc431
Revises: 53ffb1fabff6
Create Date: 2026-07-22 15:14:23.573644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dd6f5dc431'
down_revision: Union[str, Sequence[str], None] = '53ffb1fabff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус операции',
               existing_nullable=False)
    op.drop_column('reservations', 'status')
    op.add_column('rooms', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'status')
    op.add_column('reservations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Статус операции',
               existing_nullable=False)
    # ### end Alembic commands ###
