"""Fresh start: all tables

Revision ID: b4465e6c1da2
Revises: 
Create Date: 2026-07-19 22:50:52.374734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4465e6c1da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('name', sa.String(length=300), nullable=False, comment='Название отеля'),
    sa.Column('city', sa.String(length=300), nullable=False, comment='Город местоположения'),
    sa.Column('address', sa.String(length=300), nullable=False, comment='Адрес'),
    sa.Column('region', sa.String(length=300), nullable=False, comment='Регион'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('stars', sa.Integer(), nullable=False, comment='Количество звезд'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Номер телефона'),
    sa.Column('email', sa.String(length=300), nullable=True, comment='Почта'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('stars <= 5', name='stars_max_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_table('room_information',
    sa.Column('price_per_night', sa.Float(), nullable=False, comment='Цена за сутки'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='Вместимость клиентов'),
    sa.Column('size', sa.Float(), nullable=False, comment='Размер в м^2'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Тип номера'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='capacity_positive'),
    sa.CheckConstraint('size >= 12', name='size_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_information_id'), 'room_information', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('rooms',
    sa.Column('hotel_id', sa.Integer(), nullable=False, comment='Внешний ключ к отелю'),
    sa.Column('info_id', sa.Integer(), nullable=True, comment='Внешний ключ к информации о номере'),
    sa.Column('floor', sa.Integer(), nullable=False, comment='Этаж'),
    sa.Column('number', sa.Integer(), nullable=False, comment='Порядковое значение номера'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['info_id'], ['room_information.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('users_hotels',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hotels_id'), 'users_hotels', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('room_id', sa.Integer(), nullable=False, comment='Внешний ключ к номеру'),
    sa.Column('date_from', sa.DateTime(), nullable=False, comment='Дата от'),
    sa.Column('date_to', sa.DateTime(), nullable=True, comment='Дата до'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_users_hotels_id'), table_name='users_hotels')
    op.drop_table('users_hotels')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_room_information_id'), table_name='room_information')
    op.drop_table('room_information')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
