"""change column type from Room to RoomInformation 

Revision ID: d6d09748e4af
Revises: 6a1f54fba569
Create Date: 2026-07-17 13:21:08.661151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d09748e4af'
down_revision: Union[str, Sequence[str], None] = '6a1f54fba569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_information', sa.Column('type', sa.Enum('SINGLE', 'DOUBLE', 'TWIN', 'SUITE', 'FAMILY', 'APARTMENT', name='roomtype'), nullable=False, comment='Тип номера'))
    op.alter_column('room_information', 'price_per_night',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Цена за сутки',
               existing_nullable=False)
    op.alter_column('room_information', 'capacity',
               existing_type=sa.INTEGER(),
               comment='Вместимость клиентов',
               existing_nullable=False)
    op.alter_column('room_information', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Размер в м^2',
               existing_nullable=False)
    op.alter_column('rooms', 'info_id',
               existing_type=sa.INTEGER(),
               comment='Внешний ключ к информации о номере',
               existing_nullable=True)
    op.alter_column('rooms', 'floor',
               existing_type=sa.INTEGER(),
               comment='Этаж',
               existing_nullable=False)
    op.alter_column('rooms', 'number',
               existing_type=sa.INTEGER(),
               comment='Порядковое значение номера',
               existing_nullable=False)
    op.drop_column('rooms', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('type', postgresql.ENUM('SINGLE', 'DOUBLE', 'TWIN', 'SUITE', 'FAMILY', 'APARTMENT', name='roomtype'), autoincrement=False, nullable=False))
    op.alter_column('rooms', 'number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Порядковое значение номера',
               existing_nullable=False)
    op.alter_column('rooms', 'floor',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Этаж',
               existing_nullable=False)
    op.alter_column('rooms', 'info_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Внешний ключ к информации о номере',
               existing_nullable=True)
    op.alter_column('room_information', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Размер в м^2',
               existing_nullable=False)
    op.alter_column('room_information', 'capacity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Вместимость клиентов',
               existing_nullable=False)
    op.alter_column('room_information', 'price_per_night',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Цена за сутки',
               existing_nullable=False)
    op.drop_column('room_information', 'type')
    # ### end Alembic commands ###
