"""fix

Revision ID: d96592059ca6
Revises: 51ca0c1e363d
Create Date: 2026-07-19 18:41:03.575880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd96592059ca6'
down_revision: Union[str, Sequence[str], None] = '51ca0c1e363d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_information', 'type',
               existing_type=postgresql.ENUM('SINGLE', 'DOUBLE', 'TWIN', 'SUITE', 'FAMILY', 'APARTMENT', name='roomtype'),
               type_=sa.String(length=20),
               existing_comment='Тип номера',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_information', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SINGLE', 'DOUBLE', 'TWIN', 'SUITE', 'FAMILY', 'APARTMENT', name='roomtype'),
               existing_comment='Тип номера',
               existing_nullable=False)
    # ### end Alembic commands ###
