"""new column status for Reservation and indexes

Revision ID: fed232f78d46
Revises: 3c23a5413137
Create Date: 2026-07-23 18:28:54.079184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed232f78d46'
down_revision: Union[str, Sequence[str], None] = '3c23a5413137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', sa.String(length=20), nullable=False, comment='Статус бронирования'))
    op.create_index('idx_reservation_room_dates', 'reservations', ['room_id', 'date_from', 'date_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reservation_room_dates', table_name='reservations')
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###
